In [1]:
import numpy as np
import math

In [2]:
S = np.array([(440, 980), (440,670), (440,360), (440, 135), (440, -135)])
g = []
for i in S:
    g.append(math.sqrt(i[0]**2 + i[1]**2))

print(g)

[1074.2439201596628, 801.5609770940698, 568.5068161420758, 460.2445002387318, 460.2445002387318]


In [3]:
U = 220
I = np.array([5.3, 5.3, 5.3, 5.35, 5.35])
print(U/I)

[41.50943396 41.50943396 41.50943396 41.12149533 41.12149533]


In [4]:
Q = np.array([990, 990, 990, 990, 1050])
I_patrat = I**2
print(Q/I_patrat)

[35.24385902 35.24385902 35.24385902 34.58817364 36.68442659]


In [5]:
P = 440
print(P/I_patrat)

[15.66393734 15.66393734 15.66393734 15.37252162 15.37252162]


In [6]:
Q_c = np.array([0, -320, -645, -980, -1319])
I_c = np.array([0, 1.6, 3.2, 4.85, 6.5])

I_c_patrat = np.square(I_c)
X_c = np.divide(Q_c,I_c_patrat)
print(X_c)

[          nan -125.          -62.98828125  -41.66223828  -31.21893491]


C:\Users\yo\AppData\Local\Temp\ipykernel_928\3970047003.py:5: RuntimeWarning: invalid value encountered in true_divide
  X_c = np.divide(Q_c,I_c_patrat)


In [7]:
C = 1/ (100*np.pi*X_c)
print (C)

[            nan -2.54647909e-05 -5.05347788e-05 -7.64024928e-05
 -1.01960521e-04]


In [12]:
I_prim = np.array([5.3, 3.95, 2.8, 2.26, 2.8])
cosfi_p = P/(U*I_prim)
print(cosfi_p)
print( a := np.arccos(cosfi_p) )
print( np.degrees(a))

[0.37735849 0.50632911 0.71428571 0.88495575 0.71428571]
[1.18385409 1.03987377 0.77519337 0.48439734 0.77519337]
[67.82984284 59.58037828 44.4153086  27.75392336 44.4153086 ]
